### ISSUE TITLE
Suppress output to display warnings/errors only

### ISSUE THREAD

**Issue by TomaszG** [RetireNet/dotnet-retire#11]
Hello,

I couldn't find any way to reduce the output of the tool to skip debug messages. Is that possible? If not, is there any chance to get such feature?

**Comment by johnkors** [comment]
No, it's not possible at the moment — but that seems like a nice enhancement! Since the tools is using .NET Core logging functionality, it makes sense to take that in as a parameter.

`dotnet retire -loglevel debug|info|warning|error`

**Comment by johnkors** [comment]
Hi @TomaszG, i´ve pushed some changes to the tool — so now the loglevel is configurable. The output should now also be less verbose by default.

**Comment by TomaszG** [comment]
It's much better now, thanks!
