### ISSUE TITLE
Non-zero return code when vulnerabilities found

### ISSUE THREAD

**Issue by peterox** [RetireNet/dotnet-retire#49]
Could the tool return a non-zero value when vulnerabilities are found so it can be run as part of a CI pipeline.

Thanks

**Comment by ctro** [comment]
+1 for this request! Being able to run Retire in CI like Azure DevOps Pipelines would make this tool _even more_ useful.  Thanks!

**Comment by johnkors** [comment]
Fixed in release v.3.0.0 : https://www.nuget.org/packages/dotnet-retire/3.0.0
