### ISSUE TITLE
Output format glitch

### ISSUE THREAD

**Issue by josh-degraw** [RetireNet/dotnet-retire#50]
I saw this project and it looked cool so I tried it out and while the functionality seems to be doing fine, I'm running into what looks like a color formatting problem:

![image](https://user-images.githubusercontent.com/18509575/59315518-48affa00-8c77-11e9-8997-887911930201.png)

For reference's sake, I tried this on `Powershell Core 6.0.2`, and `Powershell 5.1.17134.765` and got the same result. I am getting color output on some labels (info), but getting what looks like the directive for the color output on the actual log values for them. I haven'e seen any messages other than dbug or info yet, so I don't know if there's a problem with those as well.

**Comment by johnkors** [comment]
Thanks for reporting. Might be an issue when running in powershell. I guess it's running ok in cmd?
🤷‍♂️
https://github.com/RetireNet/dotnet-retire/blob/master/dotnet-retire/Extensions/StringExtensions.cs#L6

**Comment by josh-degraw** [comment]
I wish, but it looks like it's happening in `cmd` as well:

![image](https://user-images.githubusercontent.com/18509575/59364820-b6e6d200-8cf4-11e9-88d8-5b960510b7ef.png)

On the plus side, I did at least see another color this time. It looks like it's only when it's writing the messages for `info` and `dbug` level, _sometimes_.

I initially thought it could be related to `pshazz` which I have installed and modified the styling of powershell, but again that's only for powershell, so I don't think it would affect this issue. 

If it helps, it does look like there's at least _some_ consistency, in the fact that it sseems like every time the issue happens it shows the same symbols: `[32m` before the message and `[0m[39m[49m` after.

**Comment by johnkors** [comment]
<img width="628" alt="Screenshot 2019-06-13 at 09 35 10" src="https://user-images.githubusercontent.com/206726/59412811-92572c80-8dbe-11e9-8786-2502b0651211.png">

Strange. I downloaded PowerShell Core on macOS, and that seems to be working ok.

**Comment by schreddies** [comment]
Hi, 
I can confirm having same issue for both PS and cmd.  
Machine: win10 pro 1809

**Comment by jmather** [comment]
I added `--no-color` to the command line options in https://github.com/RetireNet/dotnet-retire/pull/68
