### ISSUE TITLE
.NET Core 3.1 Support

### ISSUE THREAD

**Issue by rcollina** [RetireNet/dotnet-retire#63]
Hello,
I'd really love to use this tool in our pipeline, but it doesn't seem to be working with .NET Core 3.1.

Installed as per instructions: `dotnet tool install -g dotnet-retire`

Output:  `Tool 'dotnet-retire' (version '4.0.0') was successfully installed.`

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

The message is self-explanatory, but I've been wondering if you could publish a newer version, perhaps it'd fix this problem?

Thank you

**Comment by johnkors** [comment]
Hi, could you try https://www.nuget.org/packages/dotnet-retire/4.0.1 ?

**Comment by rcollina** [comment]
Hello,
It seems to be working - thank you for the incredibly fast feedback!
