### ISSUE TITLE
Add support for CycloneDX output format

### ISSUE THREAD

**Issue by cmenzi** [RetireNet/dotnet-retire#66]
I would be nice having a different output formats like [CycloneDX](https://cyclonedx.org/).

They also provide a [vulnerability extension](https://cyclonedx.org/ext/vulnerability/) to add all vulnerabilities for specific component.

The output is a `bom.xml` which then can be imported into [Dependency Track](https://dependencytrack.org/).

What do you think?

**Comment by johnkors** [comment]
Following up in https://github.com/CycloneDX/cyclonedx-dotnet/issues/76
