### ISSUE TITLE
Running dotnet retire on linux alpine

### ISSUE THREAD

**Issue by fukatingu** [RetireNet/dotnet-retire#67]
Hello, Am trying to run the dotnet retire on our jenkins slave (linux alpine) but we keep getting below error

```
[40m[37mtrce[39m[22m[49m: RetireNet.Packages.Tool.Services.RetireLogger[0]
      [33mLooking for System.Management.Automation/6.1.5[0m[39m[49m
[40m[37mdbug[39m[22m[49m: RetireNet.Packages.Tool.Services.DotNet.DotNetRunner[0]
      Path to `dotnet` : /root/dotnet/dotnet
[40m[37mdbug[39m[22m[49m: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore output:`  Determining projects to restore...
      
[40m[37mdbug[39m[22m[49m: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore errors:`
[40m[37mdbug[39m[22m[49m: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore exitcode:`-1
[41m[30mfail[39m[22m[49m: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Failed to `dotnet restore`. Is the current dir missing a csproj?
```

I can confirm dotnet project file does exists on the path and the same shell script works on windows machine.

Was wondering if any have got similar issue in past running dotnet retire from jenkins?

**Comment by johnkors** [comment]
I haven't tested Linux Alpine specifically, but there is a Ubuntu test run here on Github Actions: https://github.com/RetireNet/dotnet-retire/runs/757919040?check_suite_focus=true

**Comment by fukatingu** [comment]
Thanks @johnkors. Had to do dotnet build before running the retire command

**Comment by johnkors** [comment]
That's odd. The tool calls `dotnet restore` (if not done already) when `dotnet retire` is run, so it should not be necessary to build first. But good that you got it working.
