### ISSUE TITLE
Insufficient memory to continue the execution of the program

### ISSUE THREAD

**Issue by augustoproiete** [RetireNet/dotnet-retire#69]
I have a small solution with ~11 projects, running on a Windows 10 laptop with 32 GB RAM and (at the time of the run) have around 22 GB memory available to run.

However, I'm getting an out-of-memory error:

```
C:\augustoproiete\my-project>dotnet retire
info: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Scan starting
info: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Analyzing 'My.Project'
fail: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Insufficient memory to continue the execution of the program.
```

`My.Project` is an ASP .NET Core app targeting .NET Core 3.1.

**Comment by johnkors** [comment]
Jikes! That's no fun 👍 I haven't done any memory profiling on it. Will have to investigate. Thanks for reporting.

**Comment by augustoproiete** [comment]
@johnkors If it's not easy to reproduce, I'm happy to join a call/screen share if it helps diagnose the issue.
