### ISSUE TITLE
Add support for .NET 5.0

### ISSUE THREAD

**Issue by philBrown** [RetireNet/dotnet-retire#72]
If only the .NET 5.0 SDK is installed, the tool fails to run

``` none
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```

I believe this should be a simple change to the relevant `.csproj` files.

See this similar discussion regarding the Swagger CLI tool ~ https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1898

**Comment by johnkors** [comment]
Released to nuget.org as https://www.nuget.org/packages/dotnet-retire/5.0.0

Let me know if you see any issues.
